apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: backend-tests-nodejs-yljipvmo-repository
spec:
  url: https://github.com/rhtap-test-org/backend-tests-nodejs-yljipvmo