apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-nodejs-yljipvmo
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/tsscui/backend-tests-nodejs-yljipvmo:jenkins-8244094f4520042b80b952d2cc616ae2fcbfc1ab
        name: container-image  
